BRP-API/Haal-Centraal-BRP-bevragen

- docs/design_decisions.md
in tegenspraak met: ## Alle relaties kunnen embed worden
> verwijderd

- code/package-lock.json
- code/package.json
- code/src/openapi.yaml
- code/src/swagger2.0.json
This fixes vulnerabilities in various NodeJS libraries, that were are only used when executing a management command manually. Nonetheless, upgraded.
> Updated libraries and generated schema.

- docs/design_decisions.md
De ontwerpbeslissingen van het projectoverleg van 5 oktober verwerkt in de ontwerpbeslissingen
> Ontwerpbeslissingen in overleg 5 oktober verwerkt

- docs/design_decisions.md
Type van gerelateerde bij polymorfe relatie. Uitzondering bij relatieklasse, dan ook gerelateerde kunnen embedden.
> Ontwerpbeslissingen 26 okt. over polymorfe relaties en embedded van relatieklasse

- docs/productvision.md
- niet RSGB maar LO GBA
- uitgangspunten vanuit architectuurdocument "Bevraging Bronregistraties v0 1.docx" (6 nov. 2018)
- beschrijving werkwijze, o.a. behavior driven specificatie en test
> Update van productvisie

- docs/productvision.md
op verzoek van overleg 23 november uitleg/definitie van een aantal relevante begrippen toegevoegd.
> Terminologie paragraaf toegevoegd aan productvisie

- features/README.md
- features/historie_links.feature
- features/links.feature
- features/onvolledige_datum.feature
- features/partners_ouders_kinderen.feature
- features/wildcard.feature
BDD toegevoegd voor opbouw van links, onvolledige datums en actuele uuders, kinderen en partners
> links, onvolledige datums en ouders, partners, kinderen

- docs/productvision.md
ontwerpprincipers consumer first, developer first en contract first toegevoegd aan productvisie
> consumer first, developer first en contract first

- api-specificatie/Bevraging-Ingeschreven-Persoon/openapi.yaml
Diverse elementen uit LO GBA toegevoegd n.a.v. analyse en besluitvorming productowner. Datumvelden gechecked op datum onvolledig.
> Wijzigingen van issue #147 doorgevoerd

- features/foutafhandeling.feature
op basis van implementatie bij gemeente Den Haag hebben we feature voor foutafhandeling gemaakt. Ik stel voor foutafhandeling te standaardiseren, zodat clients weten welke fouten ze op welke momenten kunnen verwachten en hoe ze deze kunnen herkennen.
> feature voor foutafhandeling

- features/fields.feature
inOnderzoek en indicatieGeheim worden opgenomen zonder erom te vragen 
indien relevant
> fixes #207

- features/foutafhandeling.feature
Afhandeling van niet beschikbare bronservice
Afhandeling niet uniek burgerservicenummer
Kleine correctie in scenario's (punten achter titels
> Fixes #236

- api-specificatie/Bevraging-Ingeschreven-Persoon/openapi.yaml
> Voorletters toegevoegd aan ingeschreven_Persoon

- api-specificatie/Bevraging-Ingeschreven-Persoon/openapi.yaml
> Toevoeging standaardwaarde straatnaam in description

- api-specificatie/Bevraging-Ingeschreven-Persoon/openapi.yaml
IndicatieGeheim omgezet naar een boolean Zie #220
> Indicatie_Geheim

- features/foutafhandeling.feature
Omschrijving van de fout bij expand en fields parameter beschrijft waar de fout zit
> Foutomschrijving bij expand en fields duidelijker

- features/Voorletters.feature
toevoeging van afhandeling tweeklank-namen, afbreekstreepje en punt-naam
> uitbreiding van de voorletters feature

- api-specificatie/components.yaml
En examplewaarde voor code toegevoegd waar van toepassing.
> Examples van foutmeldingen aangepast conform feature foutmeldingen

- api-specificatie/Bevraging-Ingeschreven-Persoon/openapi.yaml
Omschrijving inhoudelijk gecorrigeerd en description eindigt nu met een "
> Aanpassing indicatiegeheim n.a.v. #268

- api-specificatie/Bevraging-Historie/openapi.yaml
Daarnaast zijn nu ook de voorletters opgenomen in de groep Naam.
> Parameter inclusiefoverledenpersonen verwijderd #255

- features/fields.feature
Fields parameter met leegwaarde is equivalent aan niet opnemen van fields parameter
Consequent doorvoeren van hele uitvoervoorspelling
> Fields=leeg

- api-specificatie/components.yaml
Examplewaarden bij invalidParams aangepast conform featurebeschrijving
> components.yaml aangepast n.a.v. #305

- api-specificatie/Bevraging-Ingeschreven-Persoon/openapi.yaml
- Groep kiesrecht is aangepast
> openapi.yaml aangepast n.a.v. #294 en #296

- api-specificatie/components.yaml
> components.yaml aangepast n.a.v. #335

- api-specificatie/Bevraging-Ingeschreven-Persoon/openapi.yaml
- (ja) of leeg verwijderd uit de omschrijving van geheimhoudingPersoonsgegevens
> openapi.yaml aangepast n.a.v. #298

- features/onbekend_waardes.feature
- features/onvolledige_datum.feature
Zie #228:
- onbekend waardes worden niet opgenomen in het antwoord
- sommige onbekend waardes worden vertaald naar een indicator
> Nieuwe feature onbekend waardes 

- api-specificatie/components.yaml
> Correctie op InvalidParams reason hier stond i.p.v. example "reason"

- api-specificatie/Landelijke tabellen/openapi.yaml
Nu ook zoekfuncties toegevoegd bij gemeenten en adellijke titels / predikaten.
> openapi.yamle landelijke tabellen aangepast uitbreiding

- api-specificatie/Bevraging-Ingeschreven-Persoon/openapi.yaml
- api-specificatie/components.yaml
Ik heb ook ook "aanhef" en "gebruikInLopendeTekst" toegevoegd en enkele examples verbeterd bij datum_onvolledig. Dit is wat mij beterft de eind-versie van ingeschreven persoon. Ik heb geen issues meer, dus volgens mij nu de review uitvoeren van alle doorgevoerde issues.
> HAL-specifieke elementen verwijderd uit de content componenten (#250)

- features/Voorletters.feature
- features/aanschrijfwijze.feature
Beschrijving van voorletters in aanschrijfnaam verwijst nu naar Voorletters.feature
> fixes #394

- features/aanhef.feature
- features/gebruik_in_lopende_tekst.feature
toegevoegd features voor naam-properties aanhef en gebruikInLopendeTekst zoals gevraagd in #334 
Voor de reviewers a.u.b. aandacht voor:
- moet in de aanhef de adellijke titel worden opgenomen?
- moet bij naamgebruik "Partner" of "Partner voor eigen" bij een persoon die zelf een adellijke titel heeft "mevrouw" of "de heer" worden opgenomen vooraan gebruikInLopendeTekst?
> beschrijving n.a.v. #334

- features/parametercombinaties.feature
recent toegevoegde toegstane parametercombinaties ook toegevoegd in overzicht parametercombinaties van parametercombinaties.feature
> nieuwe parametercombinaties toegevoegd in overzicht

- features/aanhef.feature
- features/aanschrijfwijze.feature
- features/gebruik_in_lopende_tekst.feature
na overleg met Hoge Raad van Adel
> uitwerking en correctie naamgevingsvelden 

- features/Kiesrecht.feature
terugdraaien van kiesrecht wijzigingen. Introductie van uitgeslotenVanKiesrecht. Uitgewerkt in feature.
> van kiesrecht naar uitgeslotenVanKiesrecht

- api-specificatie/Bevraging-Historie/openapi.yaml
- api-specificatie/Bevraging-Ingeschreven-Persoon/openapi.yaml
In de actueel een omschrijving verwijderd van de false waarde van uitgeslotenVanKiesrecht.
Bij de Historie endpoints het hergebruik van bestaande objecten doorgevoerd.
> Wijzigingen in de historie API + 1 actueel 

- api-specificatie/common.yaml
Toevoegen van parameters: peildatum, periodetot en periodevan
> Feature: toevoegen van periode parameters

- api-specificatie/Bevraging-Ingeschreven-Persoon/resolved/openapi.yaml
De resolved versie van de yaml toegevoegd.
> Create openapi.yaml (resolved)

- api-specificatie/Landelijke tabellen/openapi.yaml
Adellijke titel verwijderd en verbeteringen n.a.v. hergebruik uit common.Yaml en verbeteringen n.a.v. Hal-constructies doorgevoerd.
> Openai.yaml Landelijke tabellen aangepast

- api-specificatie/Bevraging-Ingeschreven-Persoon/openapi.yaml
- api-specificatie/common.yaml
peildatum, datumvan en datumtotenmet (issue #432)
> parameters voor historische bevragingen 

- api-specificatie/Bevraging-Ingeschreven-Persoon/openapi.yaml
n.a.v. aanpassen peildatum en periode parameters (issue #432)
> aanpassen description bij historie bevragingen

- api-specificatie/Bevraging-Ingeschreven-Persoon/openapi.yaml
- api-specificatie/Bevraging-Ingeschreven-Persoon/resolved/openapi.yaml
> De lengte uit het patroon verwijderd bij burgerservicenummer 

- api-specificatie/Bevraging-Ingeschreven-Persoon/openapi.yaml
- api-specificatie/Bevraging-Ingeschreven-Persoon/resolved/openapi.yaml
> 2 indicatoren doorgevoerd, Enkele descriptions aangepast en nieuwe construct fout 400

- api-specificatie/Bevraging-Ingeschreven-Persoon/openapi.yaml
- api-specificatie/Bevraging-Ingeschreven-Persoon/resolved/openapi.yaml
> Issue verwerkt link ingeschreven personen toegevoegd aan partnerhistorie

- features/partnerhistorie.feature
Scenario voor filteren op periode bij gedeeltelijk onbekende datum sluiting van een huwelijk of partnerschap
> Periode filteren bij gedeeltelijk onbekende datum sluiting

- api-specificatie/Bevraging-Ingeschreven-Persoon/openapi.yaml
- api-specificatie/Bevraging-Ingeschreven-Persoon/resolved/openapi.yaml
> Opmerkingen bij pull request #502 verwerkt

- api-specificatie/Bevraging-Ingeschreven-Persoon/openapi.yaml
- api-specificatie/Bewoning/openapi.yaml
#499 #467 #487 #449 #255 #334 #239 #497
> Diverse wijziging n.a.v. opmerkingen.

- api-specificatie/Landelijke tabellen/openapi.yaml
Uitgewerkt conform comment bij #441
> Uitgewerkte API voor Landelijke tabellen

- api-specificatie/Bevraging-Ingeschreven-Persoon/openapi.yaml
- api-specificatie/Bevraging-Ingeschreven-Persoon/resolved/openapi.yaml
> datum Opneming bij verblijfstitel verwijderd n.a.v. #26

- api-specificatie/Bevraging-Ingeschreven-Persoon/openapi.yaml
- api-specificatie/Bevraging-Ingeschreven-Persoon/resolved/openapi.yaml
- api-specificatie/Bewoning/openapi.yaml
- api-specificatie/Bewoning/resolved/openapi.yaml
> Aanpassingen n.a.v. toevoegen van geheimhoudinPersoonsgegevens 

- features/nationaliteithistorie.feature
- features/ouders.feature
> nieuwe feature nationaliteithistorie

- features/verblijfstitelhistorie.feature
https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/issues/467#issuecomment-578174617
> vervallen of intrekken verblijfstitel toegevoegd

- api-specificatie/Bevraging-Ingeschreven-Persoon/openapi.yaml
was ten onrechte weer toegevoegd in #574 terwijl verwijderd in #570
> parameter api-version verwijderd 

- api-specificatie/Bevraging-Ingeschreven-Persoon/openapi.yaml
> ingeschrevenpersonen collectie ipv ingeschrevenPersoon

- api-specificatie/Bewoning/openapi.yaml
> Links in BewoningHal moet HalLink naar ingeschrevenPersonen bevatten

- api-specificatie/Bewoning/openapi.yaml
> /haalcentraal verwijderen uit url bewoningen 

- api-specificatie/Bevraging-Ingeschreven-Persoon/openapi.yaml
- api-specificatie/Landelijke tabellen/openapi.yaml
- api-specificatie/Reisdocumenten/openapi.yaml
verwijzing naar Waardetabel i.p.v. Waardelijst n.a.v. #590. Ook enkele kleine correcties doorgevoerd.
> Waardetabel

- api-specificatie/Bewoning/openapi.yaml
- api-specificatie/Bewoning/resolved/openapi.yaml
Er is meer in de geresolvde Yaml veranderd dan ik verwacht had. Blijkbaar zijn er wijzigingen in de afgelopen tijd doorgevoerd die niet in de geresolvde versie zijn meegenomen. @fsamwel is dat een issue voor de huidige implementatie ? 
Of gebruiken @KayodeBakker  en Hans de unresolved versie ?
> Wijziging n.a.v. #603 doorgevoerd

- features/aanhef.feature
- features/aanschrijfwijze.feature
- features/gebruik_in_lopende_tekst.feature
- specificatie/openapi.yaml
- aanschrijving als geslachtsaanduiding is onbekend
- aanschrijving voor adellijke titel of predicaat wanneer geslachtsaanduiding gewijzigd is
Fixes #683
> Genderneutraal

- Releasenotes.md
- docs/releasenotes.md
- features/README.md
- specificatie/genereervariant/openapi.json
- specificatie/genereervariant/openapi.yaml
- specificatie/openapi.yaml
> Aanpassen verwijzingen naar v1.1.0 + versie aangepast naar v1.1.0 

- README.md
- docs/index.md
- docs/releasenotes.md
- specificatie/openapi.yaml
als invulling aan user stories #805 en #782 toevoegen van het A-nummer
N.B. ik heb ook al wijzigingen doorgevoerd om er v1.3.0 van te maken, behalve in het docs deel (_config.yml, user-stores-dev.md, user-stores-prod.md). @JohanBoer weet jij wat hier precies moet gebeuren om dat goed te maken?
> toevoegen A-nummer

- specificatie/openapi.yaml
> fix: NaamPersoon inheritence

- specificatie/genereervariant/openapi.json
- specificatie/genereervariant/openapi.yaml
- specificatie/openapi.yaml
Zonder deze aanpassing wordt de genereervariant in GitHub niet gegenereerd
> fix: ongeldig burgerservicenummer param example

- docs/releasenotes.md
Releasenotes voor fix 1.3.1 aangepast. 
Ik ben zo vrij dit direct te mergen.
> Aanpassen releasenotes voor 1.3.1

- features/leeftijd_bepaling.feature
> leeftijd feature uitgebreid met levenloos geboren of overleden kind

- features/adres.feature
> verbeteren adres feature

- specificatie/common.yaml
- specificatie/filter.yaml
- specificatie/geboorte.yaml
- specificatie/gezagsverhouding.yaml
- specificatie/kind.yaml
- specificatie/naam.yaml
- specificatie/nationaliteit.yaml
- specificatie/opschortingbijhouding.yaml
- specificatie/ouder.yaml
- specificatie/overlijden.yaml
- specificatie/partner.yaml
- specificatie/persoon.yaml
- specificatie/verblijfplaats.yaml
- specificatie/verblijfstitel.yaml
- specificatie/zoek-gba-personen.yaml
- specificatie/zoek-personen.yaml
Mijn opmerking tijdens sessie over de underscores bij de rate_limit headers was onjuist. 
Frank jouw gevoel klopte. De header-namen in de endpoint-definities waren wel netjes met een hyphen.
> Restricties properties2

- features/gebruik_in_lopende_tekst.feature
om deze eenvoudiger te kunnen automatiseren voor testen
> Gebruik in lopende tekst feature herschreven

- features/volledigeNaam.feature
- features/voorletters.feature
- hernoem predikaat in volledignaam feature
- toevoegen scenario in voorletters.feature
> fix(specs):

- features/kiesrecht.feature
kiesrecht feature in vorm voor proxy om gba invoer te vertalen naar Haal Centraal invoer
> Kiesrecht feature

- features/kinderen.feature
- onderscheid wat RvIG moet leveren en wat proxy moet leveren
- bepalen van type 'OnbekendKind' of 'Kind'
> aanpassen kinderen feature

- features/gebruik_in_lopende_tekst.feature
- toevoegen @proxy tag
- toevoegen regel voor gebruik partnernaam wanneer er geen partner is
- verwijderen onjuiste regel hoofdlettergebruik
> correctie gebruikInLopendeTekst

- features/zoek.feature
> feat(specs): zoek met ongeldig type

- features/leeftijd_bepaling.feature
@skip-verify toegevoegd aan scenario's die niet geautomatiseerd kunnen worden gevalideerd
> fix(leeftijd_bepaling): refactoring tbv automation

- features/volledigeNaam.feature
> opnemen titel of predicaat op basis van geslacht in volledigeNaam

- specificatie/filter.yaml
- specificatie/gba-genereervariant/openapi.json
- specificatie/gba-genereervariant/openapi.yaml
- specificatie/genereervariant/openapi.json
- specificatie/genereervariant/openapi.yaml
toestaan van een punt (.)
Fixes #983
> correctie StraatFilter pattern

- features/adres.feature
- features/verblijfplaats.feature
> uitwerken criteria verblijfplaats type en leveren adresregels

- features/kiesrecht.feature
- specificatie/gba-genereervariant/openapi.json
- specificatie/gba-genereervariant/openapi.yaml
- specificatie/genereervariant/openapi.json
- specificatie/genereervariant/openapi.yaml
- specificatie/kiesrecht.yaml
- specificatie/persoon.yaml
> Kiesrecht anders gemodelleerd n.a.v. #1034

- features/tabelwaarden.feature
> Onbekend waarde toegevoegd aan soortVerbintenis

- features/immigratie.feature
> feature voor afleiden indicatieVestigingVanuitBuitenland en vanuitVerblijfplaatsOnbekend

- features/lege-waarden.feature
> feature beschrijving leveren lege velden of lege objecten

- specificatie/genereervariant/openapi.json
- specificatie/genereervariant/openapi.yaml
- specificatie/persoon.yaml
Er stonden nog verwijzingen naar AbstractKind, AbstractOuder en AbstractPartner in de Persoon.yaml terwijl we die compononten verwijderd hebben. Ik heb de verwijzingen nu gecorrigeerd. 
Om mijn locale repo levert het resolven nog 3 warnings op. Die zijn bekend.
> Genereer issues

- specificatie/genereervariant/openapi.json
- specificatie/genereervariant/openapi.yaml
- specificatie/persoon.yaml
Deze is vervangen door datumIngangOnderzoekPersoon property
> verwijderen overbodig datum ingang onderzoek property

- features/dev/persoon-adressering-inonderzoek.feature
- specificatie/adressering.yaml
- specificatie/genereervariant/openapi.json
- specificatie/genereervariant/openapi.yaml
- test/BRP-Bevragen-postman-collection.json
- toevoeging van datumIngangOnderzoek velden aan adressering.inOnderzoek
- eerste opzet feature file voor adressering.inOnderzoek om te kijken of we over de functionaliteit hetzelfde denken
> feat: Adressering datumIngangOnderzoekXXX velden

- features/onbekend_waardes.feature
nederland en land van waar ingeschreven = geen immigratie
fixes #1170
> fix(specs): geen waarde voor datum vestiging in

- features/step_definitions/step_defs.js
- stap 'de persoon met bsn heeft de volgende gegevens' toegevoegd
- hor. en vert. dataTable support toegevoegd
> fix(automation):

- features/step_definitions/step_defs.js
vóór gba api aanroep toegevoegd
> fix(automation): uitvoeren van sql statements

- features/gba-dev/rni-gba.feature
> n.a.v. #1405

- features/gba-dev/rni-gba.feature
- features/rni.feature
> Aanpassing in Rule verduidelijk voor categorie 7

- features/leeftijd_bepaling.feature
N.a.v. check excel met feature-fails op leeftijd_bepaling.feature
> Fout herstel leeftijd bepaling

- features/bevragen/persoon/immigratie/indicatievestigingvanuitbuitenland.feature
- features/bevragen/persoon/immigratie/vanuitverblijfplaatsonbekend.feature
- features/gba-dev/onbekend_waardes_gba.feature
- features/onbekend_waardes.feature
Enkele abstract scenario's verwijderd uit onbekend_waardes omdat deze thuishoren in de verblijfplaats- en de overlijden features.
> onbekend_waardes_gba toegevoegd en onbekend_waardes aangepast

- features/bevragen/persoon/verblijfplaats/adres/onbekendwaardes.feature
- features/bevragen/persoon/verblijfplaats/dev/onbekendwaardes-gba.feature
- features/bevragen/persoon/verblijfplaats/locatie/onbekendwaardes.feature
- features/bevragen/persoon/verblijfplaats/verblijfplaatsbuitenland/onbekendwaardes.feature
- features/gba-dev/onbekend_waardes_gba.feature
- features/onbekend_waardes.feature
Scenarios voor onbekendwaardes in verblijfplaats verplaatst naar de diverse typen-folders van verblijfplaats-folder
> onbekendwaardes scenarios naar verblijfplaats verplaatst

- features/bevragen/zoek-met-geslachtsnaam-voornamen-en-gemeente-van-inschrijving/dev/gba.feature
> Gegevens-stap was fout gedefinieerd. Scenario slaagt nu

- features/bevragen/persoon/adressering/dev/fields-gba.feature
- features/bevragen/persoon/adressering/in-onderzoek.feature
> feat(specs): aanhef, aanschrijfwijze, gebruik in lopende tekst scenario's

- features/bevragen/persoon-beperkt/adressering/adres-regels/dev/autorisatie-gba.feature
- features/bevragen/persoon/adressering/adres-regels/dev/autorisatie-gba.feature
Feature die autorisatie toont van adresregels en land in adressering
In de uitwerking is een aanname gedaan m.b.t. https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/pull/1540#discussion_r1072282489
> Feature autorisatie adressering adresregels

- features/bevragen/persoon/naam/dev/aanduidingNaamgebruik-gba.feature
feature die test dat de juiste omschrijvingen worden geleverd voor aanduiding naamgebruik
> nieuwe feature voor aanduiding naamgebruik omschrijving

- features/bevragen/persoon-beperkt/opschorting-bijhouding/dev/reden-opschorting-gba.feature
- features/bevragen/persoon/opschorting-bijhouding/dev/reden-opschorting-gba.feature
nieuwe feature die test dat bij opschorting bijhouding reden de juiste omschrijving wordt geleverd.
op dit moment faalt alleen de waarde R
> feature tabelwaarden opschorting bijhouding reden

- features/bevragen/persoon-beperkt/adressering/adres-regels/dev/autorisatie-gba.feature
- features/bevragen/persoon/adressering/adres-regels/dev/autorisatie-gba.feature
tekstuele verbetering van https://github.com/BRP-API/Haal-Centraal-BRP-bevragen/pull/1563/files#r1083959443 ook doorgevoerd op adresregels features
> beter beschrijven "minimale autorisatie"

- features/bevragen/persoon/immigratie/dev/fields-gba.feature
naar aanleiding van issue #1384
> toevoegen scenario's voor fields-gba indicatieVestigingVanuitBuitenland en vanuitVerblijfplaatsOnbekend

- features/bevragen/autorisatie-gba.feature
- features/bevragen/persoon-beperkt/adressering/adres-regels/dev/autorisatie-gba.feature
- features/bevragen/persoon-beperkt/verificatie/dev/autorisatie-gba.feature
- features/bevragen/persoon/adressering/adres-regels/dev/autorisatie-gba.feature
- features/bevragen/persoon/verblijfplaats/dev/autorisatie-gba.feature
- features/bevragen/persoon/verificatie/dev/autorisatie-gba.feature
- features/bevragen/zoek-met-geslachtsnaam-en-geboortedatum/dev/parameter-autorisatie-gba.feature
- features/bevragen/zoek-met-geslachtsnaam-voornamen-en-gemeente-van-inschrijving/dev/parameter-autorisatie-gba.feature
- features/bevragen/zoek-met-nummeraanduiding-identificatie/dev/parameter-autorisatie-gba.feature
- features/bevragen/zoek-met-postcode-en-huisnummer/dev/parameter-autorisatie-gba.feature
- features/bevragen/zoek-met-straatnaam-huisnummer-en-gemeente-van-inschrijving/dev/parameter-autorisatie-gba.feature
In elk autorisatie scenario waar geen foutmelding gegeven wordt, is de Dan stap gewijzigd naar "Dan heeft de response 1 persoon"
> Wijzigen Dan stappen voor autorisatie features

- features/bevragen/autorisatie-gba.feature
correcties autorisatie feature nav opmerkingen @KayodeBakker
> Correctie autorisatie feature

- features/bevragen/persoon-beperkt/rni/dev/overzicht-gba.feature
- features/bevragen/persoon/rni/dev/overzicht-gba.feature
- verwijderen onjuiste Dan-stappen
- toevoegen tabelwaarde die gebruikt is, maar niet bij Gegeven genoemd is (heeft geen impact op automation
- toevoegen feature rni op persoon-beperkt
> Feature RNI correctie en uitbreiding

- features/bevragen/persoon-beperkt/verificatie/dev/autorisatie-gba.feature
correctie autorisatie rubrieken tbv gebruikte parameters
> correctie verificatie autorisatie gba feature

- features/bevragen/persoon/partner/dev/overzicht-gba.feature
toevoegen scenario dat #1608 toont
> Scenario voor meerdere ontbonden partners

- features/bevragen/zoek-met-postcode-en-huisnummer/dev/fout-cases-gba.feature
> correctie volgorde van foutieve parameters in foutdetail

- features/bevragen/persoon/kind/dev/kinderen-gba.feature
- features/bevragen/persoon/nationaliteit/dev/nationaliteit-gba.feature
- features/bevragen/persoon/ouder/dev/ouders-gba.feature
- features/bevragen/persoon/overlijden/dev/overlijden-onjuist-gba.feature
- features/bevragen/persoon/partner/dev/overzicht-gba.feature
- features/bevragen/persoon/verblijfstitel/dev/verblijfstitel-gba.feature
- ouders
- partners
- kinderen
- nationaliteiten
- verblijfstitel
- overlijden
> scenario's voor lege, ontbrekende of onjuiste relatie gegevens

- features/bevragen/persoon/adressering/aanschrijfwijze/dev/fields-gba.feature
- features/bevragen/persoon/verblijfplaats/dev/autorisatie-gba.feature
- features/bevragen/persoon/verblijfplaats/dev/fields-gba.feature
- features/bevragen/protocollering-gba.feature
- features/bevragen/zoek-met-geslachtsnaam-en-geboortedatum/dev/protocollering-zoek-rubrieken-gba.feature
N.a.v.#1598 - Toegevoegd 16-02-2023
Hiervoor ook enkele uitbreidingen gedaan aan fields-gba features en autorisatie feature, om de exacte velden die verwacht worden bij een fields vraag expliciet te maken en te testen.
> correctie typefouten protocollering scenario's

- features/bevragen/persoon-beperkt/geheimhouding/dev/overzicht-gba.feature
- features/bevragen/persoon-beperkt/geheimhouding/overzicht.feature
- features/bevragen/persoon/geheimhouding/dev/overzicht-gba.feature
- features/bevragen/persoon/geheimhouding/overzicht.feature
features aangepast zodat:
- geheimhouding automatisch wordt geleverd
- vragen om geheimhouding een foutmelding geeft
> Geheimhouding leveren

- features/bevragen/persoon-beperkt/verificatie/dev/autorisatie-gba.feature
- features/bevragen/persoon-beperkt/verificatie/dev/fields-gba.feature
- features/bevragen/persoon-beperkt/verificatie/fields.feature
- features/bevragen/persoon/verificatie/dev/autorisatie-gba.feature
- features/bevragen/persoon/verificatie/dev/fields-gba.feature
- features/bevragen/persoon/verificatie/fields.feature
aanpassen verificatie in features en scenario's: mag hier in fields niet om vragen
> mag niet vragen om verificatie

- features/bevragen/persoon/ouder/dev/autorisatie-gba.feature
@KayodeBakker is de rule op deze manier expliciet genoeg beschreven?
> verduidelijken rule autorisatie ouderAanduiding

- features/bevragen/fields-fout-cases-gba.feature
- features/bevragen/persoon/partner/dev/fields-gba.feature
n.a.v. #1598 "Fields die de GBA API nooit zou ontvangen"
> Gba foutmelding onderzoek

- features/bevragen/persoon/verblijfplaats/dev/autorisatie-gba.feature
n.a.v. https://github.com/BRP-API/Haal-Centraal-BRP-bevragen/pull/1651#discussion_r1118450469
> scenario's/voorbeelden die autorisatie voor verblijfplaats type tonen/testen

- features/bevragen/zoek-fout-cases-gba.feature
- features/bevragen/zoek-fout-cases.feature
ik hoor wel of de code en detail moet worden toegevoegd, aangezien dat voor de proxy tot nu toe niet nodig is geweest
> feat(specs): valide accept en content type scenario's

- features/bevragen/persoon-beperkt/naam/dev/fields-gba.feature
- features/bevragen/persoon/naam/dev/fields-gba.feature
bij vragen van groep naam moet ook geslacht worden geleverd t.b.v. volledigeNaam
> toevoegen scenario voor vragen groep naam

- features/bevragen/protocollering-gba.feature
- specificatie/genereervariant/openapi.json
- specificatie/genereervariant/openapi.yaml
- specificatie/naam.yaml
- correctie verwachtte protocollering bij vragen groep naam
- verwijderen opmerking aanduidingNaamgebruik bij PersoonBeperkt (die zit daar niet in)
> Correctie protocollering groep

- features/bevragen/persoon-beperkt/geboorte/in-onderzoek.feature
- src/BrpProxy/Generated/GbaGeboortePartial.cs
- src/BrpProxy/Profiles/GeboorteInOnderzoekConverter.cs
- src/BrpProxy/Profiles/GeboorteProfile.cs
- src/BrpProxy/Profiles/PersoonProfile.cs
feature faalt, bij zoeken wordt in geboorte geen inOnderzoek geleverd
> feature geboorte in onderzoek bij zoeken

- features/bevragen/gezag-persoon-beperkt/gezag/fields.feature
- features/bevragen/persoon/gezag/dev/gezag-meerderjarige-gba.feature
- features/bevragen/persoon/gezag/dev/test/gezag-meerderjarige-gba.feature
- features/bevragen/persoon/gezag/fields.feature
- aanvullende testscenario's voor gezag
- end to end features voor gezag
> extra features gezag

- specificatie/gba-genereervariant/openapi.json
- specificatie/gba-genereervariant/openapi.yaml
- specificatie/genereervariant/openapi.json
- specificatie/genereervariant/openapi.yaml
- specificatie/gezag.yaml
https://github.com/BRP-API/Haal-Centraal-BRP-bevragen/issues/1813
> voorbeeld gezag

- features/bevragen/persoon/verblijfplaats/adres/vastgesteld-verblijft-niet-op-adres.feature
- features/bevragen/persoon/verblijfplaats/dev/fields-gba.feature
- features/bevragen/persoon/verblijfplaats/locatie/vastgesteld-verblijft-niet-op-adres.feature
bij fields verblijfplaatsBinnenland wordt nu geen indicatieVastgesteldVerblijftNietOpAdres geleverd. Zat ook nog niet in een scenario. Is nu toegevoegd.
> vastgesteld verblijft niet op adres en vragen om verblijfplaatsBinnenland

- features/fields-filtered-Persoon.csv
Fixes https://github.com/BRP-API/Haal-Centraal-BRP-bevragen/issues/1814
> feat: deprecated velden verwijderd uit fields filtered tbv fields tool
