BRP-API/Haal-Centraal-BRP-bevragen

api-specificatie/README.md

Verwijzing naar Swaggerhub vervangen door een link die de Github-versie van de YAML direct in een Swagger-layout toont.

Readme aangepast

---

docs/design_decisions.md

Het gaat niet om alle zoekparameters uit RSGB 1.0 maar alleen die parameters die vallen onder zoeken op persoonskenmerken. Op adreskenmerken zoeken kan bij de bewoning resource.

# 96 zoekvragen uit RSGB

---

api-specificatie/components.yaml

vaste componenten om naar te verwijzen in yaml specificaties. zal hier tijdelijk in staan, want streven naar overkoepelend niveau (Geonovum/KP-API-guidelines)

Vaste componenten

---

api-specificatie/components.yaml

In het component HalLink staat nog een ref naar '#/components/schemas/Href' dat moet '#/Href' zijn.

Correctie ref in HalLink

---

api-specificatie/Bevraging-Ingeschreven-Persoon/openapi.yaml

Alle opmerkingen die tot 27-05-2019 gemaakt zijn n.a.v. implementatie bij Den Haag zijn verwerkt. De OAS3 die nu beschikbaar is op Github is bij tot 27-05-2019. Er moet nog wel review plaatsvinden op het doorvoeren van al deze issues, dus mogelijk volgen er nog aanpassingen.

Openstaande feedback-commentaar allemaal verwerkt. 

---

features/foutafhandeling.feature

Foutmelding toegevoegd voor de situatie dat de zoekvraag meer resultaten teruggeeft dan toegestaan.

Foutsituatie voor teveel resultaten

---

api-specificatie/Bevraging-Ingeschreven-Persoon/openapi.yaml

N.a.v. #197 was de componentnaam ook InOnderzoek geworden i.p.v. ReisdocumentInOnderzoek. Dit was een foutje dat nu is hersteld.

Componentnaam bij Reisdocument aangepast #197

---

api-specificatie/components.yaml

Door hergebruik van een generiek foutbericht en alleen de specifieke examples aan te vullen krijgen we in JAVA errors bij code-generatie. Deze constructie is nu verwijderd.

allOf constructie met foutbericht geelimineerd

---

api-specificatie/Bevraging-Ingeschreven-Persoon/openapi.yaml

- BSN als Query-parameter toegevoegd bij /ingeschrevenpersonen
- Example bij IndicatieCurateleRegsiter aangepast
- Elementen over Aktes en gemeente register akte verwijderd bij geboorte, overlijden, verblijfplaats 
- omschrijving aanduidingEuropeesKiesrecht aangepast
- relatie naar kind in ingeschrevenPersoon_embedded van juiste title voorzien

Openapi.yaml gewijzigd n.a.v. #327 #270 #300 #295 #263 #271

---

api-specificatie/Bevraging-Ingeschreven-Persoon/openapi.yaml

- Omschrijving indicatieGeheim aangepast
- tekst "alleen natuurlijke getallen zonder voorloopnullen" is verwijderd bij landcode
- Verwijzing naar LO GBA categorie verwijderd bij burgerservicenummer
- signaleringVerstrekkenReisdocument verwijderd
- leeftijd (ingeschreven persoon en kind)  en thuiswonendend (kind) toegevoegd 
- alle enumeraties aangepast van letter/cijger naar omschrijving
- Van alle elementen waar de toelichting niet van werd getoond de toelichting op 1 niveau hoger opgenomen
- Descriptions aangepast en alle verwijzingen naar LO GBA verwijderd.

Openapi.yaml aangepast n.a.v #298 #264 #297 #348 #341 #330 #299 #301 #326

---

api-specificatie/Bevraging-Ingeschreven-Persoon/openapi.yaml

- enumeratiewaarden bestaan nu alleen  nog uit alfanumerieke tekens en underscores
- Alle verwijzingen naar specifieke tabellen vervangen door een verwijzing naar 1 waardetabel. In de documentatie van het object opgenomen welke tabel dat inhoudelijk moet zijn,
- 2 kleine tekstfouten aangepast

openapi.yaml aangepast n.a.v. #330 en #281

---

api-specificatie/Bevraging-Ingeschreven-Persoon/openapi.yaml

Definitie van "jaar" , "maand" en "dag" in datum_onvolledig aangepast van string naar integer.

openapi.yaml aangepast n.a.v. #304

---

features/foutafhandeling.feature

voor de interne bron (gegevensmagazijn) kan een ander maximum aantal worden gehanteerd dan voor de externe bron (GBA-V). GBA-V heeft maximum van 10 voor normaal zoeken en 30 voor adres zoeken.

Geen maximaal aantal meegeven, want dat hangt af van de bron

---

api-specificatie/Bevraging-Ingeschreven-Persoon/openapi.yaml

Required parameters staan nu als voor de optionele parameters.
api-version is nu een header

openapi.yaml ingeschreven persoon aangepast n.a.v. # 387

---

api-specificatie/Bevraging-Ingeschreven-Persoon/openapi.yaml

Hoofdletter uit de enums omgezet naar kleine letter
Hoofdletter uit de linknaam ingeschrevenPersoon omgezet naar kleine letter (dus ingeshrevenpersoon) bij ouder kind en partner. 
Typefout bij reisdocument_links aangepast.

openapi.yaml ingeschreven persoon aangepast

---

api-specificatie/Bevraging-Ingeschreven-Persoon/openapi.yaml

Betreft toevoegen datumopneming bij verblijfstitel, verwijderen "Thuisonend" bij kind, element ingeschrevenPersoon met CamelCase en underscore verwijderen bij ouderaanduiding.

Kleine aanpassingen n.a.v. #393, #239, #400, #26

---

features/aanhef.feature
features/aanschrijfwijze.feature
features/gebruik_in_lopende_tekst.feature

verschillende wijzigingen aan features voor aanhef, aanschrijfwijze en gebruikInLopendeTest met betrekking tot gebruik van adellijke titels en predicaten.
Dit betreft:
- wel predicaat gebruiken wanneer men getrouwd is (geweest)
- wanneer een jonkvrouw getrouwd is of partnerschap heeft, wordt in de aanhef niet hoogwelgeboren vrouwe gebruikt, wanneer het huwelijk of partnerschap wordt ontbonden (en ze de naam van haar ex-partner niet gebruikt) wordt ze wel weer aangesproken met hoogwelgeboren vrouw
- een man mag niet de adellijke titel van zijn vrouw gebruiken

aanpassingen naamgebruik features

---

api-specificatie/Landelijke tabellen/openapi.yaml
api-specificatie/Landelijke tabellen/resolved/openapi.yaml

Blijkbaar is de resolver aangepast en worden er nu quotes om de https-foutcodes gezet. In de geresolvde versie dus meer aanpassingen die geen impact op de werking zouden mogen hebben.

allOf verwijderd uit de gemeente_links vanwege code-generaties issues.

---

api-specificatie/common.yaml

#543 hal link type vervangen door title,
invalid-params is invalidParams geworden, n.a.v. [API-standaard wijziging](https://github.com/Geonovum/KP-APIs/pull/191)

link type en invalid-params

---

features/actuele_ingeschreven_persoon.feature
features/nationaliteit.feature

nieuwe feature voor bepalen van de actuele nationaliteit:
- alleen niet-beëindigde nationaliteiten
- haal datumIngangGeldigheid uit de eerste bijbehorende categorie
- geen onjuiste nationaliteiten opnemen

feature voor nationaliteit

---

api-specificatie/Bevraging-Ingeschreven-Persoon/openapi.yaml

query parameter burgerservicenummer is gedefinieerd als array, gewijzigd explode=false en bijbehorend voorbeeld, zodat bij meerdere burgerservicenummers niet elke keer de parameternaam hoeft te worden opgenomen. Dus ?burgerservicenummer=999993653,999991723,999995078 i.p.v. ?burgerservicenummer=999993653&burgerservicenummer=999991723&burgerservicenummer=999995078

parameter burgerservicenummer explode en voorbeeld

---

api-specificatie/Bevraging-Ingeschreven-Persoon/openapi.yaml

Deze is toegevoegd omdat we van gerelateerde resources (links) ook de identificatie(s) zouden opnemen in de bevraagde resource. Echter de identificatiecodeNummeraanduiding is al opgenomen in de gegevensgroep "verblijfplaats" van de ingeschrevenPersoon

verblijfplaatsnummeraanduiding verwijderd bij ingeschrevenPersoon

---

specificatie/genereervariant/openapi.json
specificatie/genereervariant/openapi.yaml
specificatie/openapi.yaml
test/BRP-Bevragen-postman-collection.json

Verwijderen x-rate-limit headers en overbodige responses 409 (conflict), 410 (gone), 415 (Unsupported Media Type) en 429 (too many requests)
N.a.v. #641

verwijderen x-rate-limit headers en overbodige responses

---

README.md
docs/getting-started.md
redoc/index.html

P.R voor de master branch, omdat deze alleen kan worden gebruikt als hij op de master branch staat, zodat github pages het kan oppakken. Als de p.r. is gemerged, dan is de redoc versie te zien op: https://vng-realisatie.github.io/Haal-Centraal-BRP-bevragen/redoc

feature: redoc als openapi viewer

---

specificatie/openapi.yaml

Gegevens over kinderen, partners en ouders zijn nu opgenomen in de resource ingeschrevenpersoon. 
Tevens zijn alle endpoints en HAL_componenten die aan kinderen, partners of ouders gerelateerd zijn deprecated gemaakt.

Kinderen, ouders en partners in gegevensgroepen #795

---

specificatie/genereervariant/openapi.json
specificatie/genereervariant/openapi.yaml
specificatie/ouder.yaml

ik had hier eerder een opmerking over gemaakt, maar die is blijkbaar verloren gegaan in het proces.
een ouder heeft per definitie altijd een ouderAanduiding (ouder1 of ouder2). Kan dus ook in OnbekendOuder worden opgenomen.

toevoegen ouderAanduiding aan OnbekendOuder

---

features/onbekend_waardes.feature

- op basis van nieuwe specificaties v2.0.0
- bepalen onbekend datum
- in structuur andere v2.0.0 features, zodat deze eenvoudiger automatiseerbaar is
bepalen van OnbekendPartner, OnbekendOuder en OnbekendKind wordt opgenomen in resp. partners.feature, ouders.feature en konden.feature
de functionaliteit die beschreven wordt in deze feature moet in zijn geheel worden gerealiseerd in de proxy

herschrijven onbekend waardes feature

---

specificatie/gba-genereervariant/openapi.json
specificatie/gba-genereervariant/openapi.yaml
specificatie/genereervariant/openapi.json
specificatie/genereervariant/openapi.yaml
specificatie/kind.yaml
specificatie/naam.yaml

N.a.v. het besluit om de geslachtsnaam van het kind altijd op te vragen als kinderen wordt opgenomen in de fields parameter is de geslachtsnaam in die context verplicht gemaakt. Aangezien 'GbaNaamBasis' ook in andere contexten (o.a. 'GbaPersoon') wordt gebruikt is een 'GbaKindNaambasis' aangemaakt waaraan in 'GbaKind' wordt gerefereerd.

Geslachtsnaam required in GbaKind

---

features/aanhef.feature

- aanpassingen zijn gedaan tbv automation
- specificatie fouten zijn gecorrigeerd
- scenario's toegevoegd tbv bepalen eerste actuele partner en laatste ontbonden partner icm onvolledige datums
closes #1048
er scenario's die volgens mij niet kloppen volgens de rules maar zeker weet ik het niet
- scenario op regel 304, voorbeeld van regel 336. Deze persoon heeft predicaat = JV en aanduidingnaamgebruik = E en geslacht = V, dan zou  volgens mij de aanhef gelijk moeten zijn aan de aanhef horende bij de predicaat. Volgens mij is dit een voorbeeld van rule 212 en 213, maar weet ik niet zeker. Ook heb ik het gevoel dat deze twee rules die bijna identiek zijn, elkaar tegenspreken. Rule 212 zegt volgens mij dat het niet uitmaakt wat de aanduidingnaamgebruik is, maar rule 213 zegt behalve …

fix(specs): aanhef feature

---

specificatie/nationaliteit.yaml

aangezien aanduidingBijzonderNederlanderschap alleen geleverd wordt in GbaPersoon en door de proxy alleen de code gebruikt wordt, hoeft dit geen Waardetabel te zijn. De omschrijving bij de code is niet relevant.
Daarom dit veld gewijzigd in string met pattern.

wijzigen bijzonderNederlanderschap in string met pattern

---

features/volledigeNaam.feature

zodat duidelijk is wat moet gebeuren bij geslachtsnaam gelijk aan de standaardwaarde "." (betekent onbekend) en wat moet gebeuren wanneer vervolgens de hele volledigeNaam een lege string is (alle andere naamcomponenten zijn ook leeg).

toevoegen onbekende naam aan volledigeNaam feature

---

features/verblijfstitel.feature

Beschrijft dat alleen nog geldige verblijfstitel wordt geleverd.
@CathyDingemanse Datum einde verblijfstitel is gedefinieerd als "De datum waarop de verblijfstitel zijn geldigheid verliest."
Ik heb dit geïnterpreteerd als dat de verblijfstitel al op Datum einde verblijfstitel niet meer geldig is. Lees jij dat ook zo?
Fixes #1091

feature verblijfstitel

---

features/onbekend_waardes.feature

Volgens mij moet korteNaam ook leeg zijn igv van straat met onbekend waarde

fix: korteNaam bij onbekend waarde straat

---

features/adres.feature

volgens de verblijfplaats specs wordt woonplaats niet meer gevuld met gemeenteVanInschrijving.Omschrijving als woonplaatsnaam (11.50) leeg is. Geldt dit ook voor adresregel2? Scenario's op regel 123 en 141 hebben hierop betrekking.
Scenario's op regel 71 en 72 zijn volgens mij strijdig aan rule 208. Klopt dit?
Een check voor scenario's op regel 174, 191 en 212 moet de response een persoon met een leeg adressering object bevatten. Klopt dit?

fix(adres.feature): correcties tbv automation

---

specificatie/genereervariant/openapi.json
specificatie/genereervariant/openapi.yaml
specificatie/partner.yaml

Een partner met ontbindingHuwelijkPartnerschap veld geeft al aan dat de huwelijk/partnerschap met de betreffende partner is beëindigd. Of de indicatieHuwelijkPartnerschapBeeindigd veld moet naar de Partner schema component worden verplaatst zodat een consumer kan zien dat de betreffende partner is ontbonden zonder de ontbindingHuwelijkPartnerschap veld te vragen.

fix: OntbindingHuwelijkPartnerschapBasis hernoemd en indicatieHuwelijkPartnerschapBeeindigd veld verwijderd

---

features/waardetabel.feature

Closes #1150
- omschrijving uit tabel halen op basis van waarde==code
- als de waarde niet voorkomt in tabel (als code) dan alleen code leveren met de waarde
- als veld plaats geen gemeentecode bevat (niet 4 cijfers) dan is het een buitenlandse plaats of locatie en wordt omschrijving gevuld met de waarde en wordt geen code geleverd

feature voor vertalen tabel code naar omschrijving

---

features/onbekend_waardes.feature
features/verblijfstitel.feature

Closes #1200 
- verblijfstitel aanduiding 00 (onbekend) moet wel geleverd worden, zodat expliciet duidelijk wordt dat het soort verblijfstitel onbekend is >>>> verwijderd uit onbekend_waardes.feature
- verblijfstitel met aanduiding 98 (geen verblijfstitel meer) moet in zijn geheel niet geleverd worden, zodat niet de suggestie kan worden gewekt dat er wel een verblijfstitel is >>>> toegevoegd aan verblijfstitel.feature
daarnaast correctie gedaan door toevoegen elementnummers aan datum einde en ingangsdatum verblijfstitel in Gegeven stappen

Verblijfstitel 00 98

---

features/gba-dev/uitsluiting-kiesrecht.feature
features/kiesrecht.feature

- in nieuwe map gba-dev nieuw scenario toegevoegd voor de situatie dat aanduiding uitsluiting kiesrecht niet gevuld is, maar wel een einddatum uitsluiting kiesrecht
- deze situatie verwijderd uit eerste kiesrecht scenario
in gba-dev beschreven scenario hoort functioneel niet voor te komen, dus hoort niet in algemene feature (die gericht is op afnemers).
abstract scenario was niet duidelijk over wat lege kolomcellen betekenen (niet leveren, of leveren als null of als lege string, of ...)

correctie kiesrecht feature met lege aanduiding en wel einddatum

---

features/gba-dev/fields-mapping-gba.csv

bij vragen leeftijd moet ook overlijden.datum geleverd worden, omdat leeftijd niet geleverd mag worden op een overleden persoon

correctie mapping leeftijd - toevoegen overlijden

---

features/gba-dev/bag-identificatie.feature
features/step_definitions/step_defs.js

In de BRP-V komt het (nog) voor dat er incorrecte BAG-identificaties worden toegevoegd. Deze bestaan dan niet uit exact 16 cijfers. RvIG meldt dit aan de betreffende gemeenten om te corrigeren en dit gebeurt ook.
Op dit moment levert de API dan deze identificaties. Bijvoorbeeld:
```
"verblijfplaats": {
"type": "Adres",
"adresseerbaarObjectIdentificatie": "363010000123456 ",
"nummeraanduidingIdentificatie": "363200000123456 "
}
```
Dit antwoord voldoet niet aan de API specificaties (pattern voor deze velden) en mag dus niet gestuurd worden.
Ik heb een gba-dev feature gemaakt die beschrijft en test dat in dit geval de BAG identificatie niet geleverd mag worden.
N.B. de test faalt nog, omdat deze invalide waarden nog wel geleverd worden.

Feature bag identificaties

---

features/geheimhouding.feature

Omdat er nog geen scenario's zijn die functioneel beschrijven wanneer de geheimhoudingPersoonsgegevens veld wordt gevuld

specificatie: geheimhoudingPersoonsgegevens veld

---

specificatie/genereervariant/openapi.json
specificatie/genereervariant/openapi.yaml
specificatie/verblijfplaats.yaml

Aangezien we type VerblijfplaatsOnbekend nu alleen nog bepalen op basis van land (08.13.10) == 0000, kan functieAdres geen waarde hebben. Die komt alleen voor bij Adres en Locatie.
Daarom ook functieAdres verwijderd uit specificaties voor VerblijfplaatsOnbekend en VerblijfplaatsOnbekendBeperkt

verwijderen functieAdres uit verblijfplaatsOnbekend

---

specificatie/geboorte.yaml
specificatie/genereervariant/openapi.json
specificatie/genereervariant/openapi.yaml

Door het toevoegen van de inOnderzoek property aan GeboorteBeperkt en doordat Geboorte van GeboorteBeperkt afleidt, krijgt Geboorte component twee inOnderzoek properties in gegenereerde code. Dit is niet zichtbaar in SwaggerUI.
Het probleem is opgelost door de GeboorteBasis component te definieren en Geboorte en GeboorteBeperkt hiervan af te leiden

fix(specs): twee inOnderzoek properties in gegenereerde Geboorte code

---

features/bevragen/persoon/geboorte/dev/buitenlandse-plaats-gba.feature
features/bevragen/persoon/overlijden/dev/buitenlandse-plaats-gba.feature
features/bevragen/persoon/partner/dev/buitenlandse-plaats-gba.feature
features/gba-dev/waardetabel-gba.feature
features/waardetabel.feature

Correctie van de manier waarop bij een buitenlandse plaats of locatieaanduiding het veld plaats wordt gevuld.
Bij een waardetabel moet het veld code altijd een echte code uit de waardetabel bevatten. Voor een plaats kan de bron naast een code ook een vrije omschrijving bevatten. Die moet alleen in omschrijving worden gezet en niet (ook) in code.
De wijziging aan de waardetabel feature die op 9 november is gedaan wordt hiermee ongedaan gemaakt.

Correctie vullen code bij buitenlandse plaats

---

features/bevragen/autorisatie-gba.feature
features/bevragen/persoon-beperkt/adressering/adres-regels/dev/autorisatie-gba.feature
features/bevragen/persoon-beperkt/verblijfplaats/dev/autorisatie-gba.feature
features/bevragen/persoon/adressering/adres-regels/dev/autorisatie-gba.feature
features/bevragen/persoon/verblijfplaats/dev/autorisatie-gba.feature

Op verzoek van @KayodeBakker  eindigt de detail waarde bij elke autorisatie fout met een punt.
Ook correctie gemeente_code en ontbreken naam|waarde rij boven En stappen
Verwijderen foutdetail n.a.v.#1562

Toevoegen punt aan einde van elke fout detail regel voor autorisatie

---

features/bevragen/autorisatie-gba.feature

n.a.v. wijzigingen in #1577 correctie autorisatie feature op veld leeftijd: deze vereist autorisatie op geboortedatum (010310), niet op overlijdensdatum (060810), want hiervoor wordt reden opschorting bijhouding gebruikt. Voor opschorting is geen autorisatie vereist, wordt ongevraagd meegeleverd

leeftijd gebruikt alleen geboortedatum - geen overlijdensdatum

---

features/bevragen/autorisatie-gba.feature
features/bevragen/persoon-beperkt/verificatie/dev/autorisatie-gba.feature
features/bevragen/persoon-beperkt/verificatie/dev/fields-gba.feature
features/bevragen/persoon-beperkt/verificatie/fields.feature
features/bevragen/persoon/verificatie/dev/autorisatie-gba.feature
features/bevragen/persoon/verificatie/dev/fields-gba.feature
features/bevragen/persoon/verificatie/fields.feature
features/step_definitions/step_defs.js

features voor:
- leveren verificatiegegevens
- ongevraagd leveren, ook als niet gevraagd in fields
- negeren verificatie (en andere automatisch geleverde velden) voor autorisatie
N.B. de Dan stappen voor autorisatie moet wellicht worden "Dan heeft de response '1' persoon". Zie https://github.com/BRP-API/Haal-Centraal-BRP-bevragen/pull/1576#discussion_r1091586754
Dat geeft nu nog fout (verwacht dan een lege response), dus is nu nog volledig verwachte response opgenomen als Dan stap.

features verificatie

---

features/bevragen/persoon/verblijfstitel/dev/verblijfstitel-gba.feature

Naar aanleiding van #1585 toevoegen van scenario's aan de verblijfstitel-ga.feature
- scenario voor niet leveren verblijfstitel met aanduiding 98
- scenario's voor expliciet maken leveren wel/niet leveren bij datumEinde: dit is een tot-datum, dus bij datum einde vandaag is verblijfstitel niet meer geldig
- uitbreiden gegevens en fields zodat toont dan niet alleen de aanduiding, maar de hele verblijfstitel dan niet geleverd wordt

Extra scenario's verblijfstitel gba

---

features/bevragen/persoon-beperkt/opschorting-bijhouding/dev/overzicht-gba.feature
features/bevragen/persoon-beperkt/opschorting-bijhouding/overzicht.feature

Correctie van de omschrijving die bij opschortingBijhouding.reden met code='R' wordt geleverd.
Op sommige plekken stond nog "persoonslijst is aangelegd in de rni". Moet zijn "pl is aangelegd in de rni".
Zie https://github.com/BRP-API/Haal-Centraal-BRP-tabellen-bevragen/blob/master/docs/tabelwaarden.csv.
Dit zijn de waarden zoals die ook in LO BRP staan.

Opschorting rni omschrijving

---

features/bevragen/zoek-met-geslachtsnaam-voornamen-en-gemeente-van-inschrijving/dev/parameter-autorisatie-gba.feature

n.a.v. #1598:
Niet voldoende rechten
- features\bevragen\zoek-met-geslachtsnaam-voornamen-en-gemeente-van-inschrijving\dev\parameter-autorisatie-gba.feature:128
- features\bevragen\zoek-met-geslachtsnaam-voornamen-en-gemeente-van-inschrijving\dev\parameter-autorisatie-gba.feature:129

correctie gegeven rubrieken autorisatie

---

features/bevragen/persoon/gezagsverhouding/dev/gezagsverhouding-gba.feature

n.a.v. #1584 nieuw scenario toegevoegd om te testen dat gezagsverhouding op de juiste manier omgaat met:
- een waarde die nieuw of gewijzigd is in de tabel (dan de juiste omschrijving uit de tabel halen)
- een waarde die wel op een persoonslijst staat maar niet in de tabel voorkomt (dan alleen de code leveren)
scenario is nodig, omdat die nu nog faalt op beide situaties

toevoegen scenario gezagsverhouding met nieuwe of onbekende code

---

features/bevragen/raadpleeg-met-burgerservicenummer/dev/fout-cases-gba.feature
features/bevragen/raadpleeg-met-burgerservicenummer/fout-cases.feature
features/bevragen/zoek-met-geslachtsnaam-en-geboortedatum/dev/fout-cases-gba.feature
features/bevragen/zoek-met-geslachtsnaam-en-geboortedatum/fout-cases.feature
features/bevragen/zoek-met-geslachtsnaam-voornamen-en-gemeente-van-inschrijving/dev/fout-cases-gba.feature
features/bevragen/zoek-met-geslachtsnaam-voornamen-en-gemeente-van-inschrijving/fout-cases.feature
features/bevragen/zoek-met-nummeraanduiding-identificatie/dev/fout-cases-gba.feature
features/bevragen/zoek-met-nummeraanduiding-identificatie/fout-cases.feature
features/bevragen/zoek-met-postcode-en-huisnummer/dev/fout-cases-gba.feature
features/bevragen/zoek-met-postcode-en-huisnummer/fout-cases.feature
features/bevragen/zoek-met-straatnaam-huisnummer-en-gemeente-van-inschrijving/dev/fout-cases-gba.feature
features/bevragen/zoek-met-straatnaam-huisnummer-en-gemeente-van-inschrijving/fout-cases.feature

- foutmelding bij niet-gespecificeerde of onjuiste parameternaam
- features voor parametervalidatie gba

Niet gespecificeerde parameter moet fout geven

---

features/bevragen/zoek-met-geslachtsnaam-en-geboortedatum/dev/parameter-autorisatie-gba.feature
features/bevragen/zoek-met-geslachtsnaam-voornamen-en-gemeente-van-inschrijving/dev/parameter-autorisatie-gba.feature
features/bevragen/zoek-met-straatnaam-huisnummer-en-gemeente-van-inschrijving/dev/parameter-autorisatie-gba.feature

zodat de foutmelding altijd voorspelbaar is, ook wanneer er iets anders wijzigt aan de specificaties of implementatie

autorisatie foutmelding noemt in detail niet-geautoriseerde parameters op alfabetische volgorde

---

features/bevragen/persoon/rni/dev/overzicht-gba.feature

Scenario dat test dat bij een beëindigde nationaliteit - die daarom niet geleverd wordt - ook niet de RNI-deelnemergegevens daarvan worden geleverd
(in v2.0.23 gebeurt dat nog wel)

scenario rni op beëindigde nationaliteit

---

features/bevragen/fields-fout-cases.feature
features/bevragen/raadpleeg-met-burgerservicenummer/dev/fout-cases-gba.feature
features/bevragen/raadpleeg-met-burgerservicenummer/fout-cases.feature
features/bevragen/zoek-fout-cases.feature
features/bevragen/zoek-met-geslachtsnaam-en-geboortedatum/dev/fout-cases-gba.feature
features/bevragen/zoek-met-geslachtsnaam-en-geboortedatum/fout-cases.feature
features/bevragen/zoek-met-geslachtsnaam-voornamen-en-gemeente-van-inschrijving/dev/fout-cases-gba.feature
features/bevragen/zoek-met-geslachtsnaam-voornamen-en-gemeente-van-inschrijving/fout-cases.feature
features/bevragen/zoek-met-nummeraanduiding-identificatie/dev/fout-cases-gba.feature
features/bevragen/zoek-met-nummeraanduiding-identificatie/fout-cases.feature
features/bevragen/zoek-met-postcode-en-huisnummer/dev/fout-cases-gba.feature
features/bevragen/zoek-met-postcode-en-huisnummer/fout-cases.feature
features/bevragen/zoek-met-straatnaam-huisnummer-en-gemeente-van-inschrijving/dev/fout-cases-gba.feature
features/bevragen/zoek-met-straatnaam-huisnummer-en-gemeente-van-inschrijving/fout-cases.feature

Bij ontbreken van de een bij het type verwachtte parameters, wordt nu verwacht:
title: Een of meerdere parameters zijn niet correct.
code: paramsValidation

correctie fout bij ontbreken required parameter bij request type

---

features/bevragen/persoon-beperkt/rni/dev/overzicht-gba.feature
features/bevragen/persoon/rni/dev/overzicht-gba.feature

- verwijderen aanhef en aanschrijfwijze voorbeelden uit persoon-beperkt scenario's
- verwijderen inOnderzoek testgevallen voor RNI - fields inOnderzoek wordt genegeerd
- uitbreiden voorbeelden met sub-velden van datum en waardetabel

Correctie rni feature

---

features/bevragen/persoon/adressering/aanschrijfwijze/dev/fields-gba.feature
features/bevragen/persoon/adressering/gebruikinlopendetekst/dev/fields-gba.feature

- correctie burgerservicenummer in Als stap
- correctie verwachtte titel/predicaat omschrijving (casing moet gelijk zijn aan wat in database staat

correctie adressering gba features

---

features/aanschrijfwijze/adellijk.feature
features/aanschrijfwijze/dev/meerdere-partners.feature
features/bevragen/persoon/adressering/aanhef/adellijke_titel_predicaat.feature
features/bevragen/persoon/adressering/aanhef/dev/fields-gba.feature
features/bevragen/persoon/adressering/aanhef/partner_met_adellijketitel_predicaat.feature
features/bevragen/persoon/adressering/aanhef/summary.feature
features/bevragen/persoon/adressering/aanschrijfwijze/dev/fields-gba.feature
features/bevragen/persoon/adressering/gebruikinlopendetekst/dev/fields-gba.feature

- correctie aanschrijfwijze bij predicaat en naamgebruik V
- extra scenario meerdere partners, waarbij de juiste partner niet gewoon partners[0] is

Correctie aanschrijfwijze

---

features/bevragen/fields-fout-cases-gba.feature
features/bevragen/fields-fout-cases.feature

N.a.v. beslissing dat bij vragen om een automatisch geleverd veld een foutmelding moet worden gegeven
- toevoegen scenario's niet mogen vragen automatisch geleverde velden
- toevoegen fields fout cases gba feature
@MelvLee op enkele plekken geeft de implementatie op gba nu een andere invalidParams.code dan de proxy. Dat heb ik nu in de gba feature aangepast zodat die geen fout daarop geeft. Of vind jij dat een probleem en moeten gba en proxy hierop consistent werken?

Foutmelding fields automatisch

---

features/bevragen/persoon/adressering/aanhef/dev/fields-gba.feature
features/bevragen/persoon/adressering/aanschrijfwijze/dev/fields-gba.feature
features/bevragen/persoon/adressering/gebruikinlopendetekst/dev/fields-gba.feature

Er zat fout in scenario dat bij fields=adressering.aanschrijfwijze (of aanhef of gebruikInLopendeTekst) verwacht werd dat ook burgerservicenummer van de partner geleverd werd. Dat is uiteraard niet correct. 
(was copy-paste fout overgenomen van partner/dev/overzicht-gba.feature)

correctie scenario adressering samengestelde namen leveren meerdere partners

---

features/bevragen/zoek-met-geslachtsnaam-en-geboortedatum/dev/maximaal-aantal-zoekresultaten-gba.feature
features/bevragen/zoek-met-geslachtsnaam-voornamen-en-gemeente-van-inschrijving/dev/maximaal-aantal-zoekresultaten-gba.feature
features/bevragen/zoek-met-nummeraanduiding-identificatie/dev/maximaal-aantal-zoekresultaten-gba.feature
features/bevragen/zoek-met-postcode-en-huisnummer/dev/maximaal-aantal-zoekresultaten-gba.feature
features/bevragen/zoek-met-straatnaam-huisnummer-en-gemeente-van-inschrijving/dev/maximaal-aantal-zoekresultaten-gba.feature
features/step_definitions/step_defs.js

features die testen dat het maximaal aantal zoekresultaten is beperkt (nu gezet op 10).
Deze scenario's falen nog. De implementatie lijkt overleden personen en afgevoerde PL-en mee te tellen in dit aantal, terwijl die niet geleverd worden.
@MelvLee features ZoekMetNummeraanduidingIdentificatie en ZoekMetStraatHuisnummerEnGemeenteVanInschrijving zullen bij de eerste keer uitvoeren goed gaan (behalve dat ze falen op bovenstaande), maar bij een tweede keer uitvoeren komt een duplicate key value violates unique constraint "lo3_adres_idx_0" foutmelding.
Feature ZoekMetPostcodeEnHuisnummer heeft hiervoor een work around. Die work around zou voor ZoekMetNummeraanduidingIdentificatie niet werken, omdat hier op twee verschillende adressen meerdere bewoners moeten zijn.

Maximaal aantal zoekresultaten

---

features/bevragen/raadpleeg-met-burgerservicenummer/dev/geblokkeerde-pl-gba.feature
features/bevragen/zoek-met-geslachtsnaam-en-geboortedatum/dev/geblokkeerde-pl-gba.feature
features/bevragen/zoek-met-geslachtsnaam-voornamen-en-gemeente-van-inschrijving/dev/geblokkeerde-pl-gba.feature
features/bevragen/zoek-met-nummeraanduiding-identificatie/dev/geblokkeerde-pl-gba.feature
features/bevragen/zoek-met-postcode-en-huisnummer/dev/geblokkeerde-pl-gba.feature
features/bevragen/zoek-met-straatnaam-huisnummer-en-gemeente-van-inschrijving/dev/geblokkeerde-pl-gba.feature
features/step_definitions/step_defs.js

In de huidige gba API implementatie worden geblokkeerde persoonslijsten om de een of andere reden niet geleverd. daarom features/scenario's toegevoegd die tonen dat deze wel geleverd moeten worden

features voor zoeken persoon met geblokkeerde PL

---

features/bevragen/persoon-beperkt/adressering/adres-regels/dev/fields-gba.feature
features/bevragen/persoon-beperkt/rni/dev/overzicht-gba.feature

scenario dat test dat bij zoeken (persoonBeperkt) en met fields vragen om adressering alleen de adresvelden worden geleverd. Op dit moment wordt ook nog de naam en geboortedatum geleverd.

scenario gba leveren adressering

---

features/bevragen/zoek-met-postcode-en-huisnummer/dev/fout-cases-gba.feature

n.a.v. #1598 
> ##### Meerdere type validatie foutmeldingen is teveel van het goede op dit moment.
> - [ ] Scenario: Meerdere ongeldige parameters zijn opgegeven # features\bevragen\zoek-met-postcode-en-huisnummer\dev\fout-cases-gba.feature:193
Gewijzigd zodat 2 fouten op zelfde niveau veroorzaakt worden

wijziging scenario meer dan 1 foute parameter die nu ondersteund wordt

---

features/bevragen/persoon/kind/dev/kinderen-gba.feature
features/bevragen/persoon/ouder/dev/ouders-gba.feature
features/bevragen/persoon/ouder/ouders.feature
features/bevragen/persoon/partner/dev/overzicht-gba.feature

Bij ouders, partners en kinderen scenario waarbij getest wordt dat wanneer alleen inOnderzoek een waarde heeft en de andere gegevens niet, de ouder/partner/kind niet geleverd wordt.
Op dit moment is dat hoe het werkt voor ouders, maar bij partners en kinderen wordt dan een partner/kind geleverd met alleen de onderzoeksgegevens. Dit hoort voor alle relaties op dezelfde manier te werken, volgens de beschreven rule Wanneer alleen gegevens in groep 81, 82, 83, 84, 85 en/of 86 zijn opgenomen en geen gegevens in groep 1, 2, 3, 4 enz., dan wordt de ouder/partner/kind niet opgenomen.

Scenario ouder-partner-kind met alleen onderzoek

---

features/bevragen/persoon-beperkt/opschorting-bijhouding/overzicht.feature
features/bevragen/persoon/opschorting-bijhouding/dev/afgevoerde-pl-gba.feature
features/bevragen/raadpleeg-met-burgerservicenummer/dev/opschorting-bijhouding-gba.feature
features/bevragen/zoek-met-geslachtsnaam-en-geboortedatum/dev/opschorting-bijhouding-gba.feature
features/bevragen/zoek-met-geslachtsnaam-voornamen-en-gemeente-van-inschrijving/dev/opschorting-bijhouding-gba.feature
features/bevragen/zoek-met-nummeraanduiding-identificatie/dev/opschorting-bijhouding-gba.feature
features/bevragen/zoek-met-postcode-en-huisnummer/dev/opschorting-bijhouding-gba.feature
features/bevragen/zoek-met-straatnaam-huisnummer-en-gemeente-van-inschrijving/dev/opschorting-bijhouding-gba.feature

... zelfs wanneer de reden code niet bekend is
(bij een niet bekende code wordt op dit moment alleen de datum opschorting geleverd, burgerservicenummer en A-nummer, geen andere gegevens, en ook niet die code zelf)

Scenario voor wel leveren gevraagde gegevens bij andere reden dan F

---

features/bevragen/persoon/kind/dev/kinderen-gba.feature
features/step_definitions/step_defs.js

Dit was al lang geleden besloten, is blijkbaar ook al zo gebouwd (scenario slaagt), maar nog niet goed in feature gedocumenteerd. Bij deze. Zie #855, waarin de beslissing staat dit zo te doen.

toevoegen scenario levenloos geboren kind

---

features/bevragen/persoon/kind/dev/kind-naam-gba.feature
features/bevragen/persoon/naam/dev/fields-gba.feature
features/bevragen/persoon/ouder/dev/ouders-gba.feature
features/bevragen/persoon/partner/dev/fields-gba.feature
features/bevragen/persoon/verblijfplaats/dev/fields-gba.feature

check gedaan op de velden die in [features/gba-dev/fields-mapping-gba.csv](https://github.com/BRP-API/Haal-Centraal-BRP-bevragen/blob/develop/features/gba-dev/fields-mapping-gba.csv) staan. Scenario's toegevoegd of uitgebreid zodat al deze velden ergens getoond en getest worden. Daarmee wordt de fields-mapping-gba "overbodig" en kan verwijderd worden.

aanvullingen scenario's zodat fields-mapping overbodig wordt

---

docs/tabelwaarden.csv
specificatie/gba-genereervariant/openapi.json
specificatie/gba-genereervariant/openapi.yaml
specificatie/geboorte.yaml
specificatie/genereervariant/openapi.json
specificatie/genereervariant/openapi.yaml
specificatie/kiesrecht.yaml
specificatie/naam.yaml
specificatie/nationaliteit.yaml
specificatie/opschortingbijhouding.yaml
specificatie/ouder.yaml
specificatie/overlijden.yaml
specificatie/partner.yaml
specificatie/persoon.yaml
specificatie/verblijfplaats.yaml
specificatie/verblijfstitel.yaml
specificatie/zoek-personen.yaml

- omschrijvingen voor veld met waarde uit landelijke tabel zijn gewijzigd naar "wordt gevuld met waarden uit de landelijke tabel '{{naam van de tabel}}'."
- omschrijvingen voor veld met waarde uit eigen tabellen zijn gewijzigd naar "wordt gevuld met waarden voor '{{naam van de tabel}}' in 'tabelwaarden.csv'."
Wat vinden jullie van deze teksten? Is voor een afnemer het begrip "landelijke tabel" duidelijk genoeg waar dit kan worden opgezocht? Of moeten we daar een link naar de RvIG website opnemen (heb ik nu niet gedaan omdat die elk moment kan wijzigen)?
Zou ik ook het tabelnummer in de specificaties moeten opnemen?
Is de verwijzing naar 'tabelwaarden.csv' duidelijk genoeg? Kan iemand die zelf vinden in /docs/tabelwaarden.csv?

correctie verwijzing naar tabellen API

---

docs/v2/features-overzicht.md
specificatie/gba-genereervariant/openapi.json
specificatie/gba-genereervariant/openapi.yaml
specificatie/genereervariant/openapi.json
specificatie/genereervariant/openapi.yaml
specificatie/openapi.yaml
specificatie/zoek-personen.yaml

In de pool request zie je alleen dat de link naar de nieuwe fields pagina is toegevoegd.
De nieuwe fields pagina staat op klaar, zodat je die kunt bekijken en uitproberen: https://brp-api.github.io/Haal-Centraal-BRP-bevragen/v2/fields
@MelvLee @CathyDingemanse ik heb ook de verwijzing naar feature specificatie, getting started en website toegevoegd aan specificaties. En in fields description ook naar de fielden-tool

toevoegen pagina met tool voor fields samenstellen

---

docs/v2/getting-started.md

De inhoud van de links moet nog wel worden gewijzigd:
- API bijna overal BRP API Personen genoemd
- onderscheid proxy en gba variant verwijderd.
- mock is nu een mock van de proefomgeving testgevallen

Update getting-started release experimentbesluit.md

---

specificatie/brp-api/gezag/derde-v1.yaml
specificatie/brp-api/overlijden/overlijden-v1.yaml
specificatie/brp/gezag/derde-v1.yaml
specificatie/resolved/openapi.json
specificatie/resolved/openapi.yaml

- de OnbekendeDerde type is uitgebreid tbv code generatie. De object type is toegevoegd in de allOf property van OnbekendeDerde zodat de OnbekendeDerde class wordt gegenereerd bij codegeneratie met NSwag
- het inspringen van het inline embedded object is gecorrigeerd
@FrozenSync, wordt er correct code gegenereerd als de OnbekendeDerde aanpassing ook wordt doorgevoerd in de gezag-app?
fixes #1971

correcties in openapi specificaties
